### ISSUE TITLE
Can this work with custom VMs for release pipelines?

### ISSUE THREAD

**Issue by cmut7301** [jbjakobs/Postman#1]
Hello.
I have a quick question.  Our release pipelines are set up to use custom, in-house virtual machines for our agent pool.  Would this kind of setup still work (maybe with adjustments to our machines), or would we need to use the Azure Pipelines?

Thank you in advance.

**Comment by jbjakobs** [comment]
Hi,
As long as the requirements for the solution are installed, it does not matter whether it is your own VMs or Microsoft hosted agents as described in the wiki of this project. For the Microsoft hosted agent, you can see a list of installed software at:

https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

It is far from everything in this list that is required for this solution. From the list, you at least need:

Package Management
NPM 6.14.6 - see comment below
NuGet 5.7.0.6726

Tools
Git 2.28.0
Newman 5.2.0 - see comment below

Other
Visual Studio 2019 - see comment below

Comments:
Interestingly, I saw that Newman is actually already preinstalled on Microsoft hosted agent. I was not aware of this, why I in my release pipeline used NPM to install Newman. So you only need one of them.
Regarding Visual Studio, you do not need the entire Visual Studio package. This solution only requires MSBuild and .Net to build the solution & execute. So you should be able to get away with installing a subset of Visual Studio 2019.

As this solution requires the usage of both a build and a release pipeline, the above description covers the combined requirements for these pipelines.

**Comment by jbjakobs** [comment]
Closing this issue, as I believe the former comment adequately answers the questions, and no further comments have been provided.
