### ISSUE TITLE
Wrapper only seems to go one folder deep

### ISSUE THREAD

**Issue by jasoncaunt73** [jbjakobs/Postman#3]
I am adding my collections into the repo and building the wrapper to create my tests.

Now if you have the folder structure like 

MyCollection1
   MyFolder1
      Request1
      Request2
   MyFolder2
      Request3
      Request4

All is good. However, my folder structure looks like

MyCollection1
   MyFolder1
      MyFolder1a
         Request1
         Request2
      MyFolder1b
         Request1
         Request2
   MyFolder2
      Request3
      Request4

This only creates tests for MyFolder1 and MyFolder2

Is it possible to make it look where the collection tests are and give an output like

MyFolder1a, MyFolder1b and MyFolder2

**Comment by jasoncaunt73** [comment]
Even just the lowest folder would be ok. So if the tests where 3 folders deep. It would use that folder3 name

**Comment by jbjakobs** [comment]
True, the discovery of folders only looked at one level.
I have rewritten the routine to fetch folders from an arbitrary depth in the tree.
Notice that folder names must still be unique within a single collection file, independent of their depth in the tree.
Please try out the code in the following branch, both regarding discovery of test cases as well as executing the test cases in ADO.

https://github.com/jbjakobs/Postman/tree/DiscoveryPostmanFolders

**Comment by jasoncaunt73** [comment]
Excellent, thanks for your response. I will pull the branch down tomorrow and retest.
